default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: railsuser
  password: 123123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: expert_app_db_development

test:
  <<: *default
  database: expert_app_db_test

production:
  <<: *default
  database: expert_app_db_production
  username: railsuser
  password: 123123
